### ISSUE TITLE
Building RandomNumbers on Windows

### ISSUE THREAD

**Issue by GregPlowman** [sunoru/RandomNumbers.jl#19]
When building, `Pkg.build("RandomNumbers")`, on Windows without `gcc`, get error due to this:
```
check_compiler() = success(`gcc --version`)
```
Could replace by the following which fails more gracefully:
```
function check_compiler()
    try
        run(`gcc --version`)
        return true
    end
    return false
end
```
However, I noticed that `build()` on Windows tries ```run(`mingw32-make`)```,
and if that fails then downloads a binary dll. 
In this case should the `check_compiler()` be removed?
```
if have_aesni() #&& check_compiler()
    build()
else
    warn("AES-NI will not be compiled.")
end
```
I commented out the compiler check, and the build seemed to work.
Also `Pkg.test("RandomNumbers")` reported that all tests passed.

**If this is intended then definition and calls to `check_compiler()` should be removed?**

**Comment by sunoru** [comment]
Nice, thank you for reporting this and the PR. Actually I haven't tested much on Windows.
