### ISSUE TITLE
shuffle! does not work with Xorshift RNGs from this package

### ISSUE THREAD

**Issue by kozross** [sunoru/RandomNumbers.jl#23]
I am using Julia version 5. If I try the following:

    using RandomNumbers.Xorshifts
    
    r = Xoroshiro128Star()
    arr = [1,2,3,4]
    shuffle!(r, arr)

It will explode with a ``MethodError``.

**Comment by sunoru** [comment]
Thanks for reporting this issue. It's because `rand_ui52_raw` isn't implemented by this package (which I knew but I didn't realize some functions directly use it).

You can now try to clone the latest version to fix this.
