### ISSUE TITLE
Usage for common distributions

### ISSUE THREAD

**Issue by ChrisRackauckas** [sunoru/RandomNumbers.jl#26]
I think you should add to the basic section of the documentation how to use this library for generating numbers from some basic distributions. A mention of how to use it with `randn` is first, but then also how to (if it's possible) use it with Distributions.jl for random numbers from a larger class of distributions. I believe everything to do these should already be implemented (they should have an argument spot for the RNG?), so it's likely just a documentation thing to make it more accessible. If not, appropriate changes around Julia should be made to allow using these faster RNGs in place of the Base RNG for calculating random numbers from distributions.

**Comment by sunoru** [comment]
Unfortunately Distributions.jl doesn't provide functions which support different RNGs. And this is what I wanted to do next (to help implement them in Distributions.jl).

**Comment by sunoru** [comment]
See https://github.com/JuliaStats/Distributions.jl/issues/197 .

There are some functions with Rmath library so it's not so easy.

**Comment by ChrisRackauckas** [comment]
I see. What about `randn`?

**Comment by sunoru** [comment]
I think maybe it's better to document all the generic functions in `Base.Random`, which are tested here: https://github.com/sunoru/RandomNumbers.jl/blob/master/test/generic.jl

**Comment by sunoru** [comment]
Hmm... Then I found it seems unnecessary to document stuff like `randn`, `randexp`, etc., because it's well documented in Base. Let me just leave a link to http://docs.julialang.org/en/release-0.5/stdlib/numbers/#random-numbers .

**Comment by sunoru** [comment]
The official online docs are not completed, so I still add a new section here: https://github.com/sunoru/RandomNumbers.jl/blob/master/docs/src/lib/random-numbers.md#generic-functions
