### ISSUE TITLE
Build failure on 0.6

### ISSUE THREAD

**Issue by snirgaz** [sunoru/RandomNumbers.jl#27]
RandomNumbers.jl fails to build on julia 0.6 

`julia> Pkg.build("RandomNumbers")
INFO: Building RandomNumbers
====================================================================[ ERROR: RandomNumbers ]=====================================================================

LoadError: LoadError: this intrinsic must be compiled to be called
while loading /Users/snirgaz/.julia/v0.6/RandomNumbers/deps/Random123/build.jl, in expression starting on line 38
while loading /Users/snirgaz/.julia/v0.6/RandomNumbers/deps/build.jl, in expression starting on line 1

=================================================================================================================================================================

========================================================================[ BUILD ERRORS ]=========================================================================

WARNING: RandomNumbers had build errors.

 - packages with build errors remain installed in /Users/snirgaz/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("RandomNumbers")`
 - build a single package by running its `deps/build.jl` script

=================================================================================================================================================================

`

**Comment by sunoru** [comment]
Ah I'm sorry that I haven't publish the new version for 0.6 because it was not released before.

Wait a minute and you can do update once this is merged: https://github.com/JuliaLang/METADATA.jl/pull/9216

**Comment by sunoru** [comment]
Please do `Pkg.update()` to fix this.

**Comment by snirgaz** [comment]
Thanks. Great package btw.

**Comment by sunoru** [comment]
Thank you :)
