### ISSUE TITLE
Set as default

### ISSUE THREAD

**Issue by mkborregaard** [sunoru/RandomNumbers.jl#30]
Hi,
is it possible to set one of these RNGs as the system default somehow? I'd like to use these myself, but much of what I use / write is library code, so I would like to not have to pass `r` to `rand` every time.
Thanks!

**Comment by sunoru** [comment]
Hi,
I suggest you write your own `rand` functions like `myrand(args...) = rand(r, args...)` where `r` is a variable of RNG that can be accessed in scope. And when you want to use `rand` just use `myrand` instead. It's also possible to overwrite `Base.rand` but it's not recommended.
BTW, there isn't a way to change `Base.Random.GLOBAL_RNG` (which is used as default) in your library, neither should you.
Thank you for using this package :)

**Comment by mkborregaard** [comment]
Hi, thanks for the response. I have a myrand like what you describe in my juliarc.jl file already, but this doesn't work with library code. I may not have been clear - what I wanted to do was just to set the default RNG on my computer, so I could just use `rand` and let other users use the RNG they want. 
Is there some way to change Base.Random.GLOBAL_RNG locally on my system? That would do it.

**Comment by sunoru** [comment]
No, it's impossible to change `Base.Random.GLOBAL_RNG` since you can't assign variables in other modules. And you shouldn't do that because, for example, you don't know if some other libraries are also using it.
The correct way is perhaps just to export `myrand` to your users and tell them to use that.
You can also overwrite `Base.rand` like this:
```julia
module A
    using RandomNumbers
    import Base.Random: rand
    r = RandomNumbers.PCG.PCGStateSetseq()
    rand(a::Int64) = rand(r, a)
    # define a `rand` function for every possible usages of your users.
end
```
but as I mentioned before, this is really not recommended and also inconvenient.

**Comment by sunoru** [comment]
Oh I just realized you said that you defined it in `juliarc.jl`. So you can also define that in the library, use it and export it to your users.

**Comment by mkborregaard** [comment]
OK, thanks a lot though!

**Comment by sunoru** [comment]
So sorry for my previous misunderstanding (until reading that issue did I understand what you meant...). Yes so now you just need to overwrite `Base.Random.globalRNG` as https://github.com/JuliaLang/julia/commit/89359e4b7ac19cdf589109924132dd9f4afbb5cf
(but of course, it would work only on new versions of Julia)
