### ISSUE TITLE
Running benchmarks throws an error

### ISSUE THREAD

**Issue by sdwfrost** [sunoru/RandomNumbers.jl#34]
Dear @sunoru 

Very nice job on RandomNumbers. I'm trying to run the benchmarks locally, but I get an error:

```sh
julia> include("speeds.jl")
ERROR: LoadError: LoadError: UndefVarError: RNG not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
while loading common.jl, in expression starting on line 4
while loading speeds.jl, in expression starting on line 7
```

**Comment by sunoru** [comment]
Hi @sdwfrost 

Thanks for using this package! Its name was originally `RNG.jl` and changed to `RandomNumbers.jl` after the benchmarks were done, and there is still a misuse of the former name. Thanks for reminding me that :)

You can use replace `common.jl` with[ the file on master branch](https://github.com/sunoru/RandomNumbers.jl/blob/master/benchmark/common.jl) or just update your package to the latest commit to run your benchmark.
