### ISSUE TITLE
Usage with Multinomial draws

### ISSUE THREAD

**Issue by rohitvarkey** [sunoru/RandomNumbers.jl#39]
This is more of a question than an issue. Apologies if this is not the right place!

I'm porting some code to using RandomNumbers because I need parallel random number generation. I'm using an array of `Random123.Threefry4x` as an rng for each thread.

My current code does something like `rand(Multinomial(1, multinomial_probabilities)))`. Is there a way I can pass in the specific thread rng to be used for the Multinomial draw rather than the default global rng?

Thanks,
Rohit

**Comment by sunoru** [comment]
Hello. Are you using `Distributions.jl` for `Multinomial`? Unfortunately they don't support custom RNGs yet, so the only way to use this package is to implement the distribution functions by yourself.

**Comment by rohitvarkey** [comment]
> Are you using Distributions.jl for Multinomial?

I was.

> Unfortunately they don't support custom RNGs yet, so the only way to use this package is to implement the distribution functions by yourself.

I ended up doing something like that in the end.

Thanks for the clarification!
