### ISSUE TITLE
v0.7 tag

### ISSUE THREAD

**Issue by ChrisRackauckas** [sunoru/RandomNumbers.jl#40]
I see this library has been updated on master but it hasn't been tagged.

**Comment by sunoru** [comment]
Yes. The upgrade is still not complete because benchmarks and docs are still work in progress. There are also some unstable functions (especially on Windows) that I'm trying to figure out. I want to tag it after Julia 0.7 officially released.

**Comment by ChrisRackauckas** [comment]
It would be helpful if it was tagged sooner since dependent packages cannot upgrade until it's tagged.

**Comment by sunoru** [comment]
Oh, OK. Actually I don't know well how the new package manager works. What should I do to publish a new version?

**Comment by ChrisRackauckas** [comment]
I would suggest setting up attobot: https://github.com/attobot/attobot . With this it's just a few clicks to do a release.

**Comment by sunoru** [comment]
I see.. But this seems to be used before 0.7? Because it still registers packages in METADATA.jl. The update in this package should be used for the new Pkg.jl in Julia 0.7.

**Comment by ChrisRackauckas** [comment]
"General" (used to be "Curated") is created from METADATA.jl right now automatically. It updates every 5 minutes or so. So you just use the old process.

**Comment by ChrisRackauckas** [comment]
The v0.2.0 tag wasn't submitted to METADATA. You need to make sure it's submitted to get registered. I highly recommend just using attobot.
