### ISSUE TITLE
seed changed to Random.seed! on v0.7 nightly

### ISSUE THREAD

**Issue by ChrisRackauckas** [sunoru/RandomNumbers.jl#41]

**Comment by mkborregaard** [comment]
This would be good to include - not least because `Random.seed!` allows you to set the default rng for rand calls - very useful for this package.

**Comment by ChrisRackauckas** [comment]
It looks like the tag was only for v1.0? That should be backported to v0.7 so that there's a working v0.7 release.

**Comment by sunoru** [comment]
You are right, I republished a version for 0.7.

**Comment by ChrisRackauckas** [comment]
Thanks!
