### ISSUE TITLE
zero seeds give zeros

### ISSUE THREAD

**Issue by ChrisRackauckas** [sunoru/RandomNumbers.jl#48]
MWE:

```julia
using RandomNumbers
rng = Xorshifts.Xoroshiro128Plus(0)
randn(rng,Float64) # 0.0
```

**Comment by sunoru** [comment]
Yes, I think this is the expected output. If you want to specify a seed when using a RNG, you should be aware that 0 isn't a good seed.

Maybe I should add a warning here?

**Comment by ChrisRackauckas** [comment]
I would make it error

**Comment by sunoru** [comment]
You are right. I updated the code.

**Comment by PallHaraldsson** [comment]
Maybe I'm missing something, but the MWE is still broken.
